// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// Associated header
//
#include "k4asourceselectiondockcontrol.h"

// System headers
//
#include <sstream>

// Library headers
//
#include "k4aimgui_all.h"
#include <k4a/k4a.hpp>
#include <k4arecord/playback.hpp>

// Project headers
//
#include "filesystem17.h"
#include "k4aaudiomanager.h"
#include "k4aimguiextensions.h"
#include "k4aviewererrormanager.h"
#include "k4arecordingdockcontrol.h"
#include "k4aviewerutil.h"
#include "k4awindowmanager.h"
#include "calibration.h"
#include "linmath.h"
using namespace k4aviewer;

K4ASourceSelectionDockControl::K4ASourceSelectionDockControl()
{
    RefreshDevices();
}

K4ADockControlStatus K4ASourceSelectionDockControl::Show()
{
    ImGui::SetNextTreeNodeOpen(true, ImGuiCond_FirstUseEver);
    if (ImGui::TreeNode("Open Device"))
    {
        ImGuiExtensions::K4AComboBox("Device S/N",
                                     "(No available devices)",
                                     ImGuiComboFlags_None,
                                     m_connectedDevices,
                                     &m_selectedDevice);

        if (ImGui::Button("Refresh Devices"))
        {
            RefreshDevices();
        }

        ImGui::SameLine();

        const bool openAvailable = !m_connectedDevices.empty();
        {
            ImGuiExtensions::ButtonColorChanger colorChanger(ImGuiExtensions::ButtonColor::Green, openAvailable);
            if (ImGuiExtensions::K4AButton("Open Device", openAvailable))
            {
                OpenDevice();
            }
        }

        ImGui::TreePop();
    }

    ImGui::NewLine();
    ImGui::Separator();
    ImGui::NewLine();

    if (ImGui::TreeNode("Open Recording"))
    {
        if (m_filePicker.Show())
        {
            OpenRecording(m_filePicker.GetPath());
        }

        ImGui::TreePop();
    }

    return K4ADockControlStatus::Ok;
}

void K4ASourceSelectionDockControl::RefreshDevices()
{
    m_selectedDevice = -1;

    const uint32_t installedDevices = k4a_device_get_installed_count();

    m_connectedDevices.clear();

    for (uint32_t i = 0; i < installedDevices; i++)
    {
        try
        {
            k4a::device device = k4a::device::open(i);
            m_connectedDevices.emplace_back(std::make_pair(i, device.get_serialnum()));
        }
        catch (const k4a::error &)
        {
            // We can't have 2 handles to the same device, and we need to open a device handle to check
            // its serial number, so we expect devices we already have open to fail here.  Ignore those.
            //
            continue;
        }
    }

    if (!m_connectedDevices.empty())
    {
        m_selectedDevice = m_connectedDevices[0].first;
    }

    const int audioRefreshStatus = K4AAudioManager::Instance().RefreshDevices();
    if (audioRefreshStatus != SoundIoErrorNone)
    {
        std::stringstream errorBuilder;
        errorBuilder << "Failed to refresh audio devices: " << soundio_strerror(audioRefreshStatus) << "!" << std::endl
                     << "Attempting to open microphones may fail!";

        K4AViewerErrorManager::Instance().SetErrorStatus(errorBuilder.str());
    }
}

void K4ASourceSelectionDockControl::OpenDevice()
{
    try
    {
        if (m_selectedDevice < 0)
        {
            K4AViewerErrorManager::Instance().SetErrorStatus("No device selected!");
            return;
        }

        k4a::device device = k4a::device::open(static_cast<uint32_t>(m_selectedDevice));
        K4AWindowManager::Instance().PushLeftDockControl(std14::make_unique<K4ADeviceDockControl>(std::move(device)));
    }
    catch (const k4a::error &e)
    {
        K4AViewerErrorManager::Instance().SetErrorStatus(e.what());
    }
}

void K4ASourceSelectionDockControl::OpenRecording(const std17::filesystem::path &path)
{
    try
    {
        path;
        string captures_folder = "C:\\Users\\Mustafa\\Desktop\\thesis\\captures\\";

        string world2camera_file = captures_folder + "vicon_calibration\\cn03\\world2camera.txt";
        string world2camera_file2 = captures_folder + "vicon_calibration\\cn06\\world2camera.txt";

        // ICP file for the first one contains identity matrix
        // second one contains transformation matrix generated by applying icp in Cloud Compare
        // Here is the icp matrix for cn06:
        // 0.999784 -0.009129 0.018689 492.374451
        // 0.004980 0.977465 0.211038 -502.600311
        // -0.020194 -0.210899 0.977299 -498.468811
        // 0.000000 0.000000 0.000000 1.000000
        string icp_file = captures_folder + "icp\\cn03\\icp.txt";
        string icp_file2 = captures_folder + "icp\\cn06\\icp.txt";
        
        string input_video_path = captures_folder + "charuco_rotate\\cn03\\k4a_record.mkv";
        k4a::playback recording = k4a::playback::open(input_video_path.c_str());

        string input_video_path2 = captures_folder + "charuco_rotate\\cn06\\k4a_record.mkv";
        k4a::playback recording2 = k4a::playback::open(input_video_path2.c_str());

        linmath::mat4x4 se3, se3_2;
        linmath::mat4x4 c2c, c2c_id;
        
        CalibrationType calibration_type = CalibrationType::Charuco;

        Calibration calib(input_video_path, world2camera_file, icp_file, calibration_type);
        Calibration calib2(input_video_path2, world2camera_file2, icp_file2, calibration_type);
        
        // When camera2camera is used, use identity matrix for the other view
        linmath::mat4x4_identity(c2c_id);
        switch (calibration_type)
        {
        case k4aviewer::CalibrationType::Quaternion:
        case k4aviewer::CalibrationType::ICP:
            // se3' * se3_2
            calib.get_se3_inverse(se3);
            calib2.get_se3(se3_2);
            linmath::mat4x4_mul(c2c, se3, se3_2);
            break;

        case k4aviewer::CalibrationType::Charuco:
            // se3 * se3_2'
            calib.get_se3(se3);
            calib2.get_se3_inverse(se3_2);
            linmath::mat4x4_mul(c2c, se3, se3_2);
            break;
        }
        
        // Move c2c into OpenGL perspective
        move_into_GL(c2c, c2c);
        K4AWindowManager::Instance().PushLeftDockControl(std14::make_unique<K4ARecordingDockControl>(
            input_video_path, std::move(recording), std::move(recording2), c2c_id, c2c));
    }
    catch (const k4a::error &e)
    {
        K4AViewerErrorManager::Instance().SetErrorStatus(e.what());
    }
}
